version: "2"

services:
  postgres:
    image: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - FASTAPI_DB_USER=bellias
      - FASTAPI_DB_PASS=pass123
      - FASTAPI_DB_NAME=reference_letters_data
      - KEYCLOAK_DB_USER=testkeycloakuser
      - KEYCLOAK_DB_PASS=testkeycloakpassword
      - KEYCLOAK_DB_NAME=testkeycloakdb
    volumes:
      - ./src/assets/init_db:/docker-entrypoint-initdb.d/
      - dj_postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart:
      always
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: testkeycloakdb
      DB_USER: testkeycloakuser
      DB_SCHEMA: public
      DB_PASSWORD: testkeycloakpassword
      KEYCLOAK_USER: keycloakuser
      KEYCLOAK_PASSWORD: keycloakpassword
    ports:
      - 8085:8080
    depends_on:
      - postgres
    restart:
      always

volumes:
  dj_postgres_data: