version: '3'
# all services here: postgres, keycloak, minio, fastapi, vuejs, nginx
services:
  postgres:
    image: postgres
    volumes:
      - './assets/postgres/init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql'
      - 'userrepodb_data:/var/lib/postgresql/data/'
    environment:
      POSTGRES_DB: testkeycloakdb
      POSTGRES_USER: testkeycloakuser
      POSTGRES_PASSWORD: testkeycloakpassword
    restart:
      always
  
  keycloak:
    image: jboss/keycloak:16.0.1   
    volumes:
      - ./realm-export.json:/opt/jboss/keycloak/imports/realm-export.json
    command:
      - "-b 0.0.0.0 -Dkeycloak.profile.feature.upload_scripts=enabled -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: testkeycloakdb
      DB_USER: testkeycloakuser
      DB_SCHEMA: public
      DB_PASSWORD: testkeycloakpassword
      KEYCLOAK_USER: keycloakuser
      KEYCLOAK_PASSWORD: keycloakpassword
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_LOGLEVEL: DEBUG
    ports:
      - '8085:8080'
    depends_on:
      - postgres
    restart:
      always
  
  fastapi:
    restart: always
    build:
      context: .
      dockerfile: nonroot.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - keycloak

  nginx:
    image: nginx:latest
    volumes:
      - ./assets/nginx.http.config:/etc/nginx/nginx.conf
      # - ./assets/nginx.https.config:/etc/nginx/nginx.conf
      # - ./assets/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fastapi