"""Initial Migration

Revision ID: f958dda50c00
Revises: 
Create Date: 2022-03-17 12:47:45.894717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f958dda50c00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('degree', sa.String(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reference_letter_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_letter_request_id'), 'reference_letter_request', ['id'], unique=False)
    op.drop_index('idx_event_aggregate_id', table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.CHAR(length=26), autoincrement=False, nullable=False),
    sa.Column('aggregate_id', sa.CHAR(length=26), autoincrement=False, nullable=False),
    sa.Column('event_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint('char_length(aggregate_id) = 26', name='event_aggregate_id_check'),
    sa.CheckConstraint('char_length(id) = 26', name='event_id_check'),
    sa.PrimaryKeyConstraint('id', name='event_pkey'),
    sa.UniqueConstraint('aggregate_id', 'version', name='event_aggregate_id_version_key')
    )
    op.create_index('idx_event_aggregate_id', 'event', ['aggregate_id'], unique=False)
    op.drop_index(op.f('ix_reference_letter_request_id'), table_name='reference_letter_request')
    op.drop_table('reference_letter_request')
    op.drop_table('teacher')
    op.drop_table('student')
    # ### end Alembic commands ###
