apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: fastapi
  template:
    metadata:
      labels:
        component: fastapi
    spec:
      containers:
        - name: fastapi
          image: ghcr.io/panagiotis-bellias-it21871/ref-letters-fastapi-server
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: fastapi-config
          imagePullPolicy: Always
